//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksExamples
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorISBN
    {
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public string ISBN { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Title Title { get; set; }
    }
}
